spring.application.name=core
server.port=8081

spring.datasource.url=jdbc:postgresql://localhost:5432/coredb
spring.datasource.username=postgres
spring.datasource.password=sa

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

outbox.batch-size=100

outbox.max-retries=10

outbox.poll-interval=5000

outbox.initial-backoff-seconds=5

spring.kafka.bootstrap-servers=localhost:9092


spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer

bank.kafka.topic.transactions=bank.transactions